module.exports = {
  someSidebar: {
    "🌀 Start here": ["home"],
    "🤨 Pillar Memes & Lore": [
      "wtf-is-metagame/origin-story",
      "wtf-is-metagame/in-search-of-commons-that-scale",
      "wtf-is-metagame/the-coming-of-metagame",
      "wtf-is-metagame/way-of-web3-founders",
      "wtf-is-metagame/narrative-1-a-decentralized-factory",
      "wtf-is-metagame/narrative-2-a-web-of-opportunity",
      "wtf-is-metagame/metamanifesto",
    ],
    "🧐 Understanding MetaGame": [
      "how-does-it-work/wtf-is-metagame",
      "how-does-it-work/why-gamification-works",
      "how-does-it-work/phases-of-metagame",
      "how-does-it-work/how-metagame-works",
      "enter-metagame/how-to-become-a-player",
//      "how-does-it-work/obtaining-seeds",
      "how-does-it-work/become-a-founder-of-metagame",
//      "how-does-it-work/a-cautionary-tale",
      "resources/glossary",
    ],
    '🤔 What we do': [
      "what-we-do/tldr",
      "what-we-do/metasys",
      "what-we-do/mymeta",
      "what-we-do/metaos",
//      "what-we-do/events",
//      "what-we-do/metalibrary",
    ],
    '🏡 The Great Houses': [
      'great-houses/house-of-ethereum',
      'great-houses/house-of-daos',
      'great-houses/house-of-NFTs',
      'great-houses/house-of-dapps',
      'great-houses/house-of-defi',
      'great-houses/house-of-L2s',
      'great-houses/how-to-house',
    ],
    "📚 Playbooks": [
      "playbooks/meme-driven-organizations",
      "playbooks/what-why-how-of-your-dao",
      "playbooks/guilding-101",
      "playbooks/building-successful-teams",
      "playbooks/how-to-make-it-without-technical-skills",
      "playbooks/how-to-coach-eth",
      "playbooks/how-to-hackmd",
      "playbooks/entering-daos-as-a-writer",
      "playbooks/CupOJosephs-Becoming-An-Ethereum-Developer-Roadmap-and-Guide",
      "playbooks/become-a-buidler-on-ethereum-by-austin-griffith",
      "playbooks/how-to-play-twitter-by-visa",
      "playbooks/path-of-the-writer-episode-1.0",
      "playbooks/understanding-impostor-syndrome",
      "playbooks/how-to-join-a-dao-community",
      "playbooks/how-to-git-on-github-non-builder",
      "playbooks/how-to-build-a-network-for-impact",
      "playbooks/handling-fomo-in-web3",
      "playbooks/mgxp-metagame-experience-points",
      "playbooks/New-Economy-Run-By-DAOs",
    ],
  },
};
